# See https://github.com/google-github-actions/release-please-action
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build and test
        run: |
          npm ci
          npm run format:check
          npm test
          npm run build:package
          npm run build:dist
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
        if: github.ref == 'refs/heads/main'
      - name: Publish to npm
        run: npm publish package/ --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
