name: Infrastructure as Code with Terraform and Terragrunt

on:
  push:
    branches: [feat/infra-new-bucket]

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ASSUME_ROLE_ARN: arn:aws:iam::782102975611:role/OGCIO_GitHub_WebIdentity

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v2.0.0

      - name: Make init
        run: |
          cd infra
          cp .env.sample .env
          make asdf_setup

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{env.AWS_ASSUME_ROLE_ARN}}
          role-duration-seconds: 900
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: TF init
        run: |
          cd infra
          make terragrunt_init ENVIRONMENT=prod TF_MODULE=s3

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: infra-artifact
          path: infra
 
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: infra-artifact
          path: infra

      - name: TF plan
        run: |
          cd infra
          make terragrunt_init ENVIRONMENT=prod TF_MODULE=s3
