name: Publish package to GitHub Packages

on:
  # release:
  #   types: [published]
  push:
    branches: [feat/actions-publish-npm]

jobs:
  publish:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout package
        uses: actions/checkout@v2
        with:
          path: 'package/'
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: cat .npmrc
      - run: cat package.json
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
