name: Publish package to GitHub Packages

on:
  # release:
  #   types: [published]
  push:
    branches: [feat/actions-publish-npm]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout package
        uses: actions/checkout@v2
        with:
          path: 'package/'
      - name: Setting up .npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ogcio'
      - run: cat .npmrc
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
