name: Infrastructure as Code with Terraform and Terragrunt

on:
  workflow_dispatch:
    inputs:
      tf_modules:
        description: 'Terraform modules to be deployed'
        required: true
        default: 'warning'
        type: choice
        options:
          - s3
          - acm
          - cf

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ASSUME_ROLE_ARN: arn:aws:iam::782102975611:role/OGCIO_GitHub_WebIdentity
  ENVIRONMENT: prod

jobs:
  terraform:
    strategy:
      matrix:
        terraform: ${{ inputs.tf_modules }} 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v2.0.0

      - name: Configure asdf versions
        run: |
          cd infra
          cp .env.sample .env
          make asdf_setup

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{env.AWS_ASSUME_ROLE_ARN}}
          role-duration-seconds: 900
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Terragrunt init
        run: |
          cd infra
          make terragrunt_init ENVIRONMENT=${{env.ENVIRONMENT}} TF_MODULE=${{matrix.terraform}}

      - name: Terragrunt validate
        run: |
          cd infra
          make terragrunt_validate ENVIRONMENT=${{env.ENVIRONMENT}} TF_MODULE=${{matrix.terraform}}

      - name: Terragrunt plan
        run: |
          cd infra
          make terragrunt_plan ENVIRONMENT=${{env.ENVIRONMENT}} TF_MODULE=${{matrix.terraform}}

      - name: Terragrunt apply
        run: |
          cd infra
          make terragrunt_apply ENVIRONMENT=${{env.ENVIRONMENT}} TF_MODULE=${{matrix.terraform}}
